
export const actions = [
    "Add Allergies"
    , "Add Cohorts"
    , "Add Concept Proposals"
    , "Add Encounters"
    , "Add HL7 Inbound Archive"
    , "Add HL7 Inbound Exception"
    , "Add HL7 Inbound Queue"
    , "Add HL7 Source"
    , "Add Observations"
    , "Add Orders"
    , "Add Patient Identifiers"
    , "Add Patient Programs"
    , "Add Patients"
    , "Add People"
    , "Add Problems"
    , "Add Relationships"
    , "Add Users"
    , "Add Visits"
    , "Assign System Developer Role"
    , "Configure Visits"
    , "Delete Cohorts"
    , "Delete Concept Proposals"
    , "Delete Conditions"
    , "Delete Diagnoses"
    , "Delete Encounters"
    , "Delete HL7 Inbound Archive"
    , "Delete HL7 Inbound Exception"
    , "Delete HL7 Inbound Queue"
    , "Delete Medication Dispense"
    , "Delete Notes"
    , "Delete Observations"
    , "Delete Orders"
    , "Delete Patient Identifiers"
    , "Delete Patient Programs"
    , "Delete Patients"
    , "Delete People"
    , "Delete Reports"
    , "Delete Users"
    , "Delete Visits"
    , "Edit Allergies"
    , "Edit Cohorts"
    , "Edit Concept Proposals"
    , "Edit Conditions"
    , "Edit Diagnoses"
    , "Edit Encounters"
    , "Edit Notes"
    , "Edit Observations"
    , "Edit Orders"
    , "Edit Patient Identifiers"
    , "Edit Patient Programs"
    , "Edit Patients"
    , "Edit People"
    , "Edit Problems"
    , "Edit Relationships"
    , "Edit User Passwords"
    , "Edit Users"
    , "Edit Visits"
    , "Form Entry"
    , "Generate Batch of Identifiers"
    , "Get Allergies"
    , "Get Care Settings"
    , "Get Concept Attribute Types"
    , "Get Concept Classes"
    , "Get Concept Datatypes"
    , "Get Concept Map Types"
    , "Get Concept Proposals"
    , "Get Concept Reference Terms"
    , "Get Concept Sources"
    , "Get Concepts"
    , "Get Conditions"
    ,
]